"""
Django settings for telephone project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import string
import time
import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_u@*cvlhy#9(9))hbv6@w3+6hfx=btuegjm$@sxw7-ixdd^$%5'

MAIL_A_TOKEN = 'FY6DV6SXQ2MNIW44F3ZPUQ3HDUP5P22N54I7ZBTUAXMD42PS6KZA'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
	'*',
]

TEMPLATE_DEBUG = True

TEST_MODE = False

DOMAIN = 'web-tel.ru'

# Application definition

INSTALLED_APPS = (
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'telephone.main_app.templatetags',
	'telephone.main_app',
	'telephone.auth_app',
	'telephone.service_app',
	'telephone.admin_app',
)

MIDDLEWARE_CLASSES = (
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'telephone.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, 'templates')],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'telephone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql_psycopg2',
		'NAME': 'telephonedb' if DEBUG else 'videomesrf',
		'USER': 'postgres' if DEBUG else 'videomesrf',
		'PASSWORD': 'qwaszx@1',
		'HOST': 'localhost' if DEBUG else 'pg.sweb.ru',
		'PORT': '5432',
	}
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATICFILES_DIRS = (
	'static/content/fonts',
	'static/content/themes/',
	# 'static/content/scripts/coffee',
	'static/content/scripts/javascript',
	'static/content/scripts/shared',
	'static/content',
	'static/content/images'
)

STATIC_URL = '/static/content/'

# STATIC_ROOT = 'static/r_content/'

TEMPLATE_DIRS = (
	os.path.join(BASE_DIR,  'templates'),
	os.path.join(BASE_DIR,  'main_app/templates'),
	os.path.join(BASE_DIR,  'auth_app/templates'),
	os.path.join(BASE_DIR,  'admin_app/templates'),
)

LOGIN_URL = '/auth/login/'

S_KEY = 'e6eddf38406a4fa03d09'

API_URLS = {
	'api': {
		'host': 'https://api.zadarma.com',
		'api_version': '/v1',
		'statistics': '/statistics',
		'statisticspbx': '/statistics/pbx',
	},
	'base_api_url': 'https://api.zadarma.com',
	'api_version': '/v1',
	'get_record': '/record',
	'statistics': '/statistics',
	'statisticspbx': '/statistics/pbx',
	'oauth': {
		'host': 'https://oauth.yandex.ru',
		'authorize': '/authorize?response_type=code',
		'token': '/token'
	},
	'mail': {
		'host': 'https://pddimp.yandex.ru',
		'create_mail': '/api2/admin/email/add',
		'update_mail': '/api2/admin/email/edit',
	},
	'disk': {
		''
	}
}

TIME_CORRECTION = 3

O_AUTH_ID = '52a0d804d54b45ef8c309088af6d444d'

O_AUTH_SECRET = '962a08aad3974d3395c140a77b0f26ac'

CORS_ORIGIN_ALLOW_ALL = (
	'*'
)

DELIMITER = ';'

DATE_CLIENT_FORMAT = '%d.%m.%Y'
DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'
DATETIME_FORMAT_START = '%Y-%m-%d 00:00:00'
DATETIME_FORMAT_END = '%Y-%m-%d 23:59:59'

LOGGING = {
	'version': 1,
	'disable_existing_loggers': False,
	'formatters': {
		'verbose': {
			'format': "\n[%(asctime)s] %(levelname)s %(message)s",
			'datefmt': "%d/%b/%Y %H:%M:%S"
		},
		'simple': {
			'format': '%(levelname)s %(message)s'
		},
	},
	'handlers': {
		'django': {
			'level': 'INFO',
			'class': 'logging.handlers.RotatingFileHandler',
			'maxBytes': 10*1024*1024,
			'backupCount': 0,
			'filename': os.path.join(BASE_DIR,  'debug.log'),
			'formatter': 'verbose',
		},
		'app_logger_handler': {
			'level': 'INFO',
			'class': 'logging.handlers.RotatingFileHandler',
			'maxBytes': 10*1024*1024,
			'backupCount': 0,
			'filename': os.path.join(BASE_DIR,  'log.log'),
			'formatter': 'verbose',
		}
	},
	'loggers': {
		'django': {
			'handlers': ['django'],
			'level': 'INFO',
			'propagate': True,
		},
		'app_logger': {
			'handlers': ['app_logger_handler'],
			'level': 'INFO',
			'propagate': True,
		},
	},
}